package com.nictko.services.responseother.crgbledgerrespponse

import com.google.gson.annotations.SerializedName


data class Data (

  @SerializedName("bc_agent_id"                   ) var bcAgentId                 : String? = null,
  @SerializedName("office"                        ) var office                    : String? = null,
  @SerializedName("state"                         ) var state                     : String? = null,
  @SerializedName("district"                      ) var district                  : String? = null,
  @SerializedName("zone"                          ) var zone                      : String? = null,
  @SerializedName("br_name"                       ) var brName                    : String? = null,
  @SerializedName("lnk_br_code"                   ) var lnkBrCode                 : String? = null,
  @SerializedName("ur_rl"                         ) var urRl                      : String? = null,
  @SerializedName("bc_name"                       ) var bcName                    : String? = null,
  @SerializedName("con_no"                        ) var conNo                     : String? = null,
  @SerializedName("saving_acc_no"                 ) var savingAccNo               : String? = null,
  @SerializedName("pan_no"                        ) var panNo                     : String? = null,
  @SerializedName("csp_loc"                       ) var cspLoc                    : String? = null,
  @SerializedName("cif_acc_opening"               ) var cifAccOpening             : String? = null,
  @SerializedName("cif_acc_opening_comm"          ) var cifAccOpeningComm         : String? = null,
  @SerializedName("digital_vkyc_acc_opening"      ) var digitalVkycAccOpening     : String? = null,
  @SerializedName("digital_vkyc_acc_opening_comm" ) var digitalVkycAccOpeningComm : String? = null,
  @SerializedName("insta_acc_opening"             ) var instaAccOpening           : String? = null,
  @SerializedName("insta_acc_opening_comm"        ) var instaAccOpeningComm       : String? = null,
  @SerializedName("c_kyc"                         ) var cKyc                      : String? = null,
  @SerializedName("c_kyc_comm"                    ) var cKycComm                  : String? = null,
  @SerializedName("adhar_based_txn_count"         ) var adharBasedTxnCount        : String? = null,
  @SerializedName("adhar_based_txn_amt"           ) var adharBasedTxnAmt          : String? = null,
  @SerializedName("adhar_based_txn_comm"          ) var adharBasedTxnComm         : String? = null,
  @SerializedName("acc_based_txn_count"           ) var accBasedTxnCount          : String? = null,
  @SerializedName("acc_based_txn_amt"             ) var accBasedTxnAmt            : String? = null,
  @SerializedName("acc_based_txn_comm"            ) var accBasedTxnComm           : String? = null,
  @SerializedName("rupay_based_txn_count"         ) var rupayBasedTxnCount        : String? = null,
  @SerializedName("rupay_based_txn_amt"           ) var rupayBasedTxnAmt          : String? = null,
  @SerializedName("rupay_based_txn_comm"          ) var rupayBasedTxnComm         : String? = null,
  @SerializedName("imps_based_txn_count"          ) var impsBasedTxnCount         : String? = null,
  @SerializedName("imps_based_txn_amt"            ) var impsBasedTxnAmt           : String? = null,
  @SerializedName("imps_based_txn_comm"           ) var impsBasedTxnComm          : String? = null,
  @SerializedName("offline_apy"                   ) var offlineApy                : String? = null,
  @SerializedName("offline_apy_comm"              ) var offlineApyComm            : String? = null,
  @SerializedName("offline_pmjjby"                ) var offlinePmjjby             : String? = null,
  @SerializedName("offline_pmjjby_comm"           ) var offlinePmjjbyComm         : String? = null,
  @SerializedName("offline_pmsby"                 ) var offlinePmsby              : String? = null,
  @SerializedName("offline_pmsby_comm"            ) var offlinePmsbyComm          : String? = null,
  @SerializedName("online_apy"                    ) var onlineApy                 : String? = null,
  @SerializedName("online_apy_comm"               ) var onlineApyComm             : String? = null,
  @SerializedName("online_pmjjby"                 ) var onlinePmjjby              : String? = null,
  @SerializedName("online_pmjjby_comm"            ) var onlinePmjjbyComm          : String? = null,
  @SerializedName("online_pmsby"                  ) var onlinePmsby               : String? = null,
  @SerializedName("online_pmsby_comm"             ) var onlinePmsbyComm           : String? = null,
  @SerializedName("adhar_seeding"                 ) var adharSeeding              : String? = null,
  @SerializedName("adhar_seeding_comm"            ) var adharSeedingComm          : String? = null,
  @SerializedName("passbook_printing"             ) var passbookPrinting          : String? = null,
  @SerializedName("passbook_printing_comm"        ) var passbookPrintingComm      : String? = null,
  @SerializedName("e_banking"                     ) var eBanking                  : String? = null,
  @SerializedName("e_banking_comm"                ) var eBankingComm              : String? = null,
  @SerializedName("kyc_address_varify"            ) var kycAddressVarify          : String? = null,
  @SerializedName("kyc_address_varify_comm"       ) var kycAddressVarifyComm      : String? = null,
  @SerializedName("notice"                        ) var notice                    : String? = null,
  @SerializedName("notice_comm"                   ) var noticeComm                : String? = null,
  @SerializedName("sbi_g_pai"                     ) var sbiGPai                   : String? = null,
  @SerializedName("sbi_g_pai_comm"                ) var sbiGPaiComm               : String? = null,
  @SerializedName("incentive_avrg_blnc"           ) var incentiveAvrgBlnc         : String? = null,
  @SerializedName("incentive_avrg_blnc_comm"      ) var incentiveAvrgBlncComm     : String? = null,
  @SerializedName("tol_csp_comm"                  ) var tolCspComm                : String? = null,
  @SerializedName("igst"                          ) var igst                      : String? = null,
  @SerializedName("bill_amt"                      ) var billAmt                   : String? = null,
  @SerializedName("csp_shr"                       ) var cspShr                    : String? = null,
  @SerializedName("csp_tds"                       ) var cspTds                    : String? = null,
  @SerializedName("net_pay"                       ) var netPay                    : String? = null,
  @SerializedName("incentive_act_date"            ) var incentiveActDate          : String? = null

)