package com.nictko.services.responseother.ubinledgerresponse

import com.google.gson.annotations.SerializedName


data class Data (

  @SerializedName("loan_RECOVERY_COUNT"           ) var loanRECOVERYCOUNT         : String? = null,
  @SerializedName("sms_ALERT_COUNT"               ) var smsALERTCOUNT             : String? = null,
  @SerializedName("loan_RECOVERY_COMMISSION"      ) var loanRECOVERYCOMMISSION    : String? = null,
  @SerializedName("bbps_TRANSACTION_COUNT"        ) var bbpsTRANSACTIONCOUNT      : String? = null,
  @SerializedName("bbps_TRANSACTION_AMOUNT"       ) var bbpsTRANSACTIONAMOUNT     : String? = null,
  @SerializedName("fixed_CHARGES_BC"              ) var fixedCHARGESBC            : String? = null,
  @SerializedName("total_COMMISSION_AMOUNT"       ) var totalCOMMISSIONAMOUNT     : String? = null,
  @SerializedName("block_DEBIT_CARD_COM"          ) var blockDEBITCARDCOM         : String? = null,
  @SerializedName("sms_ALERT_COMMISSION"          ) var smsALERTCOMMISSION        : String? = null,
  @SerializedName("bbps_TRANSACTION_COMMISSION"   ) var bbpsTRANSACTIONCOMMISSION : String? = null,
  @SerializedName("loan_RECOVERY_AMOUNT"          ) var loanRECOVERYAMOUNT        : String? = null,
  @SerializedName("eli_EASE_COMMISSION"           ) var eliEASECOMMISSION         : String? = null,
  @SerializedName("new_CHEQUE_BOOK_REQUEST_COUNT" ) var newCHEQUEBOOKREQUESTCOUNT : String? = null,
  @SerializedName("block_DEBIT_CARD_COUNT"        ) var blockDEBITCARDCOUNT       : String? = null,
  @SerializedName("new_CHEQUE_BOOK_REQUEST_COM"   ) var newCHEQUEBOOKREQUESTCOM   : String? = null,
  @SerializedName("imps_TXN_COUNT"                ) var impsTXNCOUNT              : String? = null,
  @SerializedName("rupay_CARD_AMOUNT"             ) var rupayCARDAMOUNT           : String? = null,
  @SerializedName("mobile_SEEDING_COUNT"          ) var mobileSEEDINGCOUNT        : String? = null,
  @SerializedName("aadhar_SEEDING_COM"            ) var aadharSEEDINGCOM          : String? = null,
  @SerializedName("financial_COMMISSION"          ) var financialCOMMISSION       : String? = null,
  @SerializedName("eli_EASE_TOTAL_TXN"            ) var eliEASETOTALTXN           : String? = null,
  @SerializedName("mini_STATEMENT_COM"            ) var miniSTATEMENTCOM          : String? = null,
  @SerializedName("mobile_SEEDING_COM"            ) var mobileSEEDINGCOM          : String? = null,
  @SerializedName("aeps_TXN_COUNT"                ) var aepsTXNCOUNT              : String? = null,
  @SerializedName("rupay_CARD_TXN_COUNT"          ) var rupayCARDTXNCOUNT         : String? = null,
  @SerializedName("stop_CHEQUE_COUNT"             ) var stopCHEQUECOUNT           : String? = null,
  @SerializedName("mini_STATEMENT_COUNT"          ) var miniSTATEMENTCOUNT        : String? = null,
  @SerializedName("neft_TXN_COUNT"                ) var neftTXNCOUNT              : String? = null,
  @SerializedName("stop_CHEQUE_COM"               ) var stopCHEQUECOM             : String? = null,
  @SerializedName("aadhar_SEEDING_COUNT"          ) var aadharSEEDINGCOUNT        : String? = null,
  @SerializedName("apply_NEW_DEBIT_CARD_COUNT"    ) var applyNEWDEBITCARDCOUNT    : String? = null,
  @SerializedName("apply_NEW_DEBIT_CARD_COM"      ) var applyNEWDEBITCARDCOM      : String? = null,
  @SerializedName("sba_ACCOUNT"                   ) var sbaACCOUNT                : String? = null,
  @SerializedName("no_LOGIN_DAYS"                 ) var noLOGINDAYS               : String? = null,
  @SerializedName("ekyc_COUNT"                    ) var ekycCOUNT                 : String? = null,
  @SerializedName("village"                       ) var village                   : String? = null,
  @SerializedName("ekyc_COM"                      ) var ekycCOM                   : String? = null,
  @SerializedName("fd_COUNT"                      ) var fdCOUNT                   : String? = null,
  @SerializedName("state"                         ) var state                     : String? = null,
  @SerializedName("pan_NUMBER"                    ) var panNUMBER                 : String? = null,
  @SerializedName("branch"                        ) var branch                    : String? = null,
  @SerializedName("branch_ID"                     ) var branchID                  : String? = null,
  @SerializedName("agent_ID"                      ) var agentID                   : String? = null,
  @SerializedName("vle_NAME"                      ) var vleNAME                   : String? = null,
  @SerializedName("phone_No"                      ) var phoneNo                   : String? = null,
  @SerializedName("district"                      ) var district                  : String? = null,
  @SerializedName("fi_COUNT"                      ) var fiCOUNT                   : String? = null,
  @SerializedName("fi_AMOUNT"                     ) var fiAMOUNT                  : String? = null,
  @SerializedName("neft_AMOUNT"                   ) var neftAMOUNT                : String? = null,
  @SerializedName("csp_TDS"                       ) var cspTDS                    : String? = null,
  @SerializedName("pmjjby_COM"                    ) var pmjjbyCOM                 : String? = null,
  @SerializedName("final_PAYABLE"                 ) var finalPAYABLE              : String? = null,
  @SerializedName("apy_COM"                       ) var apyCOM                    : String? = null,
  @SerializedName("pmsby_COM"                     ) var pmsbyCOM                  : String? = null,
  @SerializedName("rd_COUNT"                      ) var rdCOUNT                   : String? = null,
  @SerializedName("apy_COUNT"                     ) var apyCOUNT                  : String? = null,
  @SerializedName("tpd_AMOUNT"                    ) var tpdAMOUNT                 : String? = null,
  @SerializedName("shg_TXN_COUNT"                 ) var shgTXNCOUNT               : String? = null,
  @SerializedName("imps_AMOUNT"                   ) var impsAMOUNT                : String? = null,
  @SerializedName("fd_COM"                        ) var fdCOM                     : String? = null,
  @SerializedName("shg_AMOUNT"                    ) var shgAMOUNT                 : String? = null,
  @SerializedName("rd_COM"                        ) var rdCOM                     : String? = null,
  @SerializedName("tpd_TXN_COUNT"                 ) var tpdTXNCOUNT               : String? = null,
  @SerializedName("pmjjby_COUNT"                  ) var pmjjbyCOUNT               : String? = null,
  @SerializedName("pmsby_COUNT"                   ) var pmsbyCOUNT                : String? = null,
  @SerializedName("aeps_AMOUNT"                   ) var aepsAMOUNT                : String? = null,
  @SerializedName("bca_SHARE"                     ) var bcaSHARE                  : String? = null

)