package com.nictko.services.responseother.mpgbledgerresponse

import com.google.gson.annotations.SerializedName


data class Data (

  @SerializedName("bc_agent_id"                                 ) var bcAgentId                              : String? = null,
  @SerializedName("office"                                      ) var office                                 : String? = null,
  @SerializedName("state"                                       ) var state                                  : String? = null,
  @SerializedName("district"                                    ) var district                               : String? = null,
  @SerializedName("zone"                                        ) var zone                                   : String? = null,
  @SerializedName("br_name"                                     ) var brName                                 : String? = null,
  @SerializedName("lnk_br_code"                                 ) var lnkBrCode                              : String? = null,
  @SerializedName("ur_rl"                                       ) var urRl                                   : String? = null,
  @SerializedName("bc_name"                                     ) var bcName                                 : String? = null,
  @SerializedName("contact_no"                                  ) var contactNo                              : String? = null,
  @SerializedName("saving_acc_no"                               ) var savingAccNo                            : String? = null,
  @SerializedName("pan_no"                                      ) var panNo                                  : String? = null,
  @SerializedName("csp_loc"                                     ) var cspLoc                                 : String? = null,
  @SerializedName("total_no_acc"                                ) var totalNoAcc                             : String? = null,
  @SerializedName("remuniration_acc_open"                       ) var remunirationAccOpen                    : String? = null,
  @SerializedName("onus_cash_deposit_mpgb"                      ) var onusCashDepositMpgb                    : String? = null,
  @SerializedName("onus_cash_deposit_amount"                    ) var onusCashDepositAmount                  : String? = null,
  @SerializedName("onus_cash_deposit_comm"                      ) var onusCashDepositComm                    : String? = null,
  @SerializedName("offus_cash_deposit_other_bank"               ) var offusCashDepositOtherBank              : String? = null,
  @SerializedName("offus_cash_deposit_amount"                   ) var offusCashDepositAmount                 : String? = null,
  @SerializedName("offus_cash_deposit_comm"                     ) var offusCashDepositComm                   : String? = null,
  @SerializedName("onus_cash_withdrawal_mpgb"                   ) var onusCashWithdrawalMpgb                 : String? = null,
  @SerializedName("onus_cash_withdrawal_amount"                 ) var onusCashWithdrawalAmount               : String? = null,
  @SerializedName("onus_cash_withdrawal_comm"                   ) var onusCashWithdrawalComm                 : String? = null,
  @SerializedName("offus_cash_withdrawal_other_bank"            ) var offusCashWithdrawalOtherBank           : String? = null,
  @SerializedName("offus_cash_withdrawal_other_bank_amount"     ) var offusCashWithdrawalOtherBankAmount     : String? = null,
  @SerializedName("offus_cash_withdrawal_other_bank_comm"       ) var offusCashWithdrawalOtherBankComm       : String? = null,
  @SerializedName("fund_transfer"                               ) var fundTransfer                           : String? = null,
  @SerializedName("fund_transfer_amount"                        ) var fundTransferAmount                     : String? = null,
  @SerializedName("fund_transfer_comm"                          ) var fundTransferComm                       : String? = null,
  @SerializedName("intrasol_money_transfer_same_branch"         ) var intrasolMoneyTransferSameBranch        : String? = null,
  @SerializedName("intrasol_money_transfer_same_branch_amount"  ) var intrasolMoneyTransferSameBranchAmount  : String? = null,
  @SerializedName("intrasol_money_transfer_same_branch_comm"    ) var intrasolMoneyTransferSameBranchComm    : String? = null,
  @SerializedName("neft_total"                                  ) var neftTotal                              : String? = null,
  @SerializedName("neft_amount"                                 ) var neftAmount                             : String? = null,
  @SerializedName("neft_comm"                                   ) var neftComm                               : String? = null,
  @SerializedName("intrasol_money_transfer_other_branch"        ) var intrasolMoneyTransferOtherBranch       : String? = null,
  @SerializedName("intrasol_money_transfer_other_branch_amount" ) var intrasolMoneyTransferOtherBranchAmount : String? = null,
  @SerializedName("intrasol_money_transfer_other_branch_comm"   ) var intrasolMoneyTransferOtherBranchComm   : String? = null,
  @SerializedName("total_txn"                                   ) var totalTxn                               : String? = null,
  @SerializedName("total_txn_amount"                            ) var totalTxnAmount                         : String? = null,
  @SerializedName("total_txn_comm"                              ) var totalTxnComm                           : String? = null,
  @SerializedName("pmjjby_enrolment"                            ) var pmjjbyEnrolment                        : String? = null,
  @SerializedName("pmjjby_comm"                                 ) var pmjjbyComm                             : String? = null,
  @SerializedName("pmsby_enrolment"                             ) var pmsbyEnrolment                         : String? = null,
  @SerializedName("pmsby_comm"                                  ) var pmsbyComm                              : String? = null,
  @SerializedName("rupay_activation"                            ) var rupayActivation                        : String? = null,
  @SerializedName("rupay_activation_comm"                       ) var rupayActivationComm                    : String? = null,
  @SerializedName("aadhar_seeded"                               ) var aadharSeeded                           : String? = null,
  @SerializedName("aadhar_seeded_comm"                          ) var aadharSeededComm                       : String? = null,
  @SerializedName("cheque_collection"                           ) var chequeCollection                       : String? = null,
  @SerializedName("cheque_collection_comm"                      ) var chequeCollectionComm                   : String? = null,
  @SerializedName("mobile_seeding"                              ) var mobileSeeding                          : String? = null,
  @SerializedName("mobile_seeding_comm"                         ) var mobileSeedingComm                      : String? = null,
  @SerializedName("apy_enrollments"                             ) var apyEnrollments                         : String? = null,
  @SerializedName("apy_enrollments_comm"                        ) var apyEnrollmentsComm                     : String? = null,
  @SerializedName("bill_amount"                                 ) var billAmount                             : String? = null,
  @SerializedName("csp_share"                                   ) var cspShare                               : String? = null,
  @SerializedName("csp_tds"                                     ) var cspTds                                 : String? = null,
  @SerializedName("recovery"                                    ) var recovery                               : String? = null,
  @SerializedName("net_payable"                                 ) var netPayable                             : String? = null

)