package com.nictko.services.responseother.boilledgerresponse

import com.google.gson.annotations.SerializedName


data class Data (

  @SerializedName("agent_id"                 ) var agentId                : String? = null,
  @SerializedName("office"                   ) var office                 : String? = null,
  @SerializedName("district"                 ) var district               : String? = null,
  @SerializedName("zone"                     ) var zone                   : String? = null,
  @SerializedName("branch_name"              ) var branchName             : String? = null,
  @SerializedName("link_branch_code"         ) var linkBranchCode         : String? = null,
  @SerializedName("urban_rural"              ) var urbanRural             : String? = null,
  @SerializedName("bc_name"                  ) var bcName                 : String? = null,
  @SerializedName("contact_numb"             ) var contactNumb            : String? = null,
  @SerializedName("saving_accn"              ) var savingAccn             : String? = null,
  @SerializedName("pan_no"                   ) var panNo                  : String? = null,
  @SerializedName("csp_location"             ) var cspLocation            : String? = null,
  @SerializedName("total_account_opened"     ) var totalAccountOpened     : String? = null,
  @SerializedName("remuniration_accn_opened" ) var remunirationAccnOpened : String? = null,
  @SerializedName("total_transction"         ) var totalTransction        : String? = null,
  @SerializedName("rem_transc"               ) var remTransc              : String? = null,
  @SerializedName("adhar_seeding"            ) var adharSeeding           : String? = null,
  @SerializedName("rem_adhar_seeding"        ) var remAdharSeeding        : String? = null,
  @SerializedName("rupay_activation"         ) var rupayActivation        : String? = null,
  @SerializedName("pmjjby"                   ) var pmjjby                 : String? = null,
  @SerializedName("rem_pmjjby"               ) var remPmjjby              : String? = null,
  @SerializedName("pmsby"                    ) var pmsby                  : String? = null,
  @SerializedName("rem_pmsby"                ) var remPmsby               : String? = null,
  @SerializedName("total_rd"                 ) var totalRd                : String? = null,
  @SerializedName("rem_rd"                   ) var remRd                  : String? = null,
  @SerializedName("total_td"                 ) var totalTd                : String? = null,
  @SerializedName("rem_td"                   ) var remTd                  : String? = null,
  @SerializedName("total_chequebook"         ) var totalChequebook        : String? = null,
  @SerializedName("rem_checkbook"            ) var remCheckbook           : String? = null,
  @SerializedName("stop_cheque"              ) var stopCheque             : String? = null,
  @SerializedName("rem_stop_cheque"          ) var remStopCheque          : String? = null,
  @SerializedName("debit_card"               ) var debitCard              : String? = null,
  @SerializedName("rem_debit_card"           ) var remDebitCard           : String? = null,
  @SerializedName("debit_card_block"         ) var debitCardBlock         : String? = null,
  @SerializedName("rem_debit_card_block"     ) var remDebitCardBlock      : String? = null,
  @SerializedName("passbook_printing"        ) var passbookPrinting       : String? = null,
  @SerializedName("rem_passbook_printing"    ) var remPassbookPrinting    : String? = null,
  @SerializedName("jeevan_praman_patra"      ) var jeevanPramanPatra      : String? = null,
  @SerializedName("rem_jeevan_praman"        ) var remJeevanPraman        : String? = null,
  @SerializedName("add_incentive"            ) var addIncentive           : String? = null,
  @SerializedName("rem_add_incentive"        ) var remAddIncentive        : String? = null,
  @SerializedName("mobile_seeding"           ) var mobileSeeding          : String? = null,
  @SerializedName("rem_mobile_seeding"       ) var remMobileSeeding       : String? = null,
  @SerializedName("tot_cheq_col"             ) var totCheqCol             : String? = null,
  @SerializedName("rem_cheq_col"             ) var remCheqCol             : String? = null,
  @SerializedName("tot_apy"                  ) var totApy                 : String? = null,
  @SerializedName("rem_apy"                  ) var remApy                 : String? = null,
  @SerializedName("recovery"                 ) var recovery               : String? = null,
  @SerializedName("rec_recovery"             ) var recRecovery            : String? = null,
  @SerializedName("mutual_fund"              ) var mutualFund             : String? = null,
  @SerializedName("rem_mutual"               ) var remMutual              : String? = null,
  @SerializedName("tot_loan"                 ) var totLoan                : String? = null,
  @SerializedName("rem_tot_loan"             ) var remTotLoan             : String? = null,
  @SerializedName("curr_acc"                 ) var currAcc                : String? = null,
  @SerializedName("rem_curr_acc"             ) var remCurrAcc             : String? = null,
  @SerializedName("nrml_rec_amnt"            ) var nrmlRecAmnt            : String? = null,
  @SerializedName("nrml_rec_comm"            ) var nrmlRecComm            : String? = null,
  @SerializedName("tot_loan_disbur_amnt"     ) var totLoanDisburAmnt      : String? = null,
  @SerializedName("tot_loan_disbur_comm"     ) var totLoanDisburComm      : String? = null,
  @SerializedName("tot_loan_repay_amnt"      ) var totLoanRepayAmnt       : String? = null,
  @SerializedName("tot_loan_repay_comm"      ) var totLoanRepayComm       : String? = null,
  @SerializedName("ppf_ssa_scss_count"       ) var ppfSsaScssCount        : String? = null,
  @SerializedName("ppf_ssa_scss_comm"        ) var ppfSsaScssComm         : String? = null,
  @SerializedName("nps_count"                ) var npsCount               : String? = null,
  @SerializedName("nps_comm"                 ) var npsComm                : String? = null,
  @SerializedName("sgb_frsb_count"           ) var sgbFrsbCount           : String? = null,
  @SerializedName("sgb_frsb_comm"            ) var sgbFrsbComm            : String? = null,
  @SerializedName("tcs_mis"                  ) var tcsMis                 : String? = null,
  @SerializedName("round_tripping"           ) var roundTripping          : String? = null,
  @SerializedName("grand_total"              ) var grandTotal             : String? = null,
  @SerializedName("igst"                     ) var igst                   : String? = null,
  @SerializedName("bill_amt"                 ) var billAmt                : String? = null,
  @SerializedName("csp_share"                ) var cspShare               : String? = null,
  @SerializedName("csp_tds"                  ) var cspTds                 : String? = null,
  @SerializedName("rd_pen_rec"               ) var rdPenRec               : String? = null,
  @SerializedName("pen_rec"                  ) var penRec                 : String? = null,
  @SerializedName("state"                    ) var state                  : String? = null,
  @SerializedName("net_payable"              ) var netPayable             : String? = null

)